"""
Berlekamp-Massey Algorithm for LFSR Reconstruction

The Berlekamp-Massey algorithm finds the shortest Linear Feedback Shift Register (LFSR)
that can generate a given binary sequence. For a degree-N LFSR, you need at least 2N
consecutive bits to uniquely determine the feedback polynomial.

Reference: Massey, J. (1969). "Shift-register synthesis and BCH decoding."
IEEE Transactions on Information Theory, 15(1), 122-127.
"""

import numpy as np


def berlekamp_massey(sequence):
    """
    Berlekamp-Massey algorithm to find the minimal LFSR for a binary sequence.
    
    Args:
        sequence: List or array of binary values (0 or 1)
        
    Returns:
        connection_polynomial: List of tap positions (e.g., [10, 3, 0] for x^10 + x^3 + 1)
        
    The connection polynomial C(x) represents the feedback taps.
    If C(x) = 1 + c_1*x + c_2*x^2 + ... + c_L*x^L, then taps are at positions where c_i = 1.
    """
    sequence = np.array(sequence, dtype=int)
    n = len(sequence)
    
    # Initialize
    c = np.zeros(n, dtype=int)  # Connection polynomial
    c[0] = 1
    b = np.zeros(n, dtype=int)  # Previous connection polynomial
    b[0] = 1
    
    L = 0  # Current length of LFSR
    m = 1  # Steps since last length change
    
    for N in range(n):
        # Calculate discrepancy
        d = sequence[N]
        for i in range(1, L + 1):
            d ^= c[i] & sequence[N - i]
        
        if d == 1:
            # Save current c
            temp = c.copy()
            
            # Update c
            for i in range(n - m):
                c[i + m] ^= b[i]
            
            if 2 * L <= N:
                L = N + 1 - L
                b = temp
                m = 1
            else:
                m += 1
        else:
            m += 1
    
    # Extract tap positions from connection polynomial
    taps = [i for i in range(len(c)) if c[i] == 1]
    
    if len(taps) == 0:
        return [0]
    
    # Convert to standard polynomial notation [degree, tap1, tap2, ..., 0]
    degree = taps[-1]
    polynomial = [degree] + taps[1:-1] + [0]
    
    return polynomial, L


def reconstruct_lfsr_state(sequence, polynomial):
    """
    Given a sequence and the known polynomial, reconstruct the LFSR initial state.
    
    Args:
        sequence: Observed bit sequence
        polynomial: LFSR polynomial (e.g., [10, 3, 0])
        
    Returns:
        initial_state: The initial state that produces this sequence
    """
    degree = polynomial[0]
    
    # The first 'degree' bits are the initial state
    if len(sequence) < degree:
        raise ValueError(f"Need at least {degree} bits to reconstruct {degree}-bit LFSR state")
    
    # Initial state is the first N bits (in reverse order for our LFSR implementation)
    initial_state = list(sequence[:degree])
    
    return initial_state


def verify_lfsr(sequence, polynomial, initial_state):
    """
    Verify that the given polynomial and initial state produce the observed sequence.
    
    Args:
        sequence: Observed bit sequence
        polynomial: LFSR polynomial
        initial_state: LFSR initial state
        
    Returns:
        match: True if LFSR generates the sequence, False otherwise
        generated: The sequence generated by the LFSR
    """
    from gold_code import LFSR
    
    lfsr = LFSR(polynomial, initial_state)
    generated = lfsr.generate(len(sequence))
    
    match = np.array_equal(sequence, generated)
    
    return match, generated


def reconstruct_gold_code_lfsr(hop_sequence, k=3):
    """
    Reconstruct the Gold code LFSR from observed frequency hops.
    
    Args:
        hop_sequence: Array of hop indices (0-7 for k=3)
        k: Number of bits per hop (default 3)
        
    Returns:
        polynomial: Reconstructed LFSR polynomial
        initial_state: Reconstructed initial state
        degree: LFSR degree
    """
    # Convert hop indices to bit sequence
    # Each hop is k bits: hop_index = b0*4 + b1*2 + b2*1 for k=3
    bit_sequence = []
    for hop in hop_sequence:
        # Convert to k-bit binary (MSB first)
        bits = [(hop >> (k - 1 - i)) & 1 for i in range(k)]
        bit_sequence.extend(bits)
    
    bit_sequence = np.array(bit_sequence, dtype=int)
    
    # Run Berlekamp-Massey
    polynomial, degree = berlekamp_massey(bit_sequence)
    
    # Reconstruct initial state
    initial_state = reconstruct_lfsr_state(bit_sequence, polynomial)
    
    print(f"Reconstructed LFSR:")
    print(f"  Degree: {degree}")
    print(f"  Polynomial: {polynomial}")
    print(f"  Initial State: {initial_state}")
    
    # Verify
    match, generated = verify_lfsr(bit_sequence, polynomial, initial_state)
    print(f"  Verification: {'✓ MATCH' if match else '✗ MISMATCH'}")
    
    if not match:
        # Show where mismatch occurs
        diff_idx = np.where(bit_sequence != generated)[0]
        if len(diff_idx) > 0:
            print(f"  First mismatch at bit {diff_idx[0]}")
    
    return polynomial, initial_state, degree


if __name__ == "__main__":
    # Test with a known sequence
    print("="*60)
    print("Testing Berlekamp-Massey Algorithm")
    print("="*60)
    
    # Test 1: Simple known LFSR
    print("\nTest 1: x^4 + x + 1 (taps at [4, 1, 0])")
    from gold_code import LFSR
    
    test_poly = [4, 1, 0]
    test_initial = [0, 0, 0, 1]
    
    lfsr = LFSR(test_poly, test_initial)
    test_sequence = lfsr.generate(30)
    
    print(f"Original sequence (30 bits): {test_sequence}")
    
    # Reconstruct
    reconstructed_poly, reconstructed_L = berlekamp_massey(test_sequence)
    reconstructed_state = reconstruct_lfsr_state(test_sequence, reconstructed_poly)
    
    print(f"Reconstructed polynomial: {reconstructed_poly}")
    print(f"Reconstructed state: {reconstructed_state}")
    print(f"Reconstructed degree: {reconstructed_L}")
    
    # Verify
    match, generated = verify_lfsr(test_sequence, reconstructed_poly, reconstructed_state)
    print(f"Verification: {'✓ PASS' if match else '✗ FAIL'}")
    
    # Test 2: Degree-10 polynomial (your Gold code)
    print("\n" + "="*60)
    print("Test 2: x^10 + x^3 + 1 (your Gold code polynomial)")
    print("="*60)
    
    gold_poly = [10, 3, 0]
    gold_initial = [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
    
    lfsr_gold = LFSR(gold_poly, gold_initial)
    gold_sequence = lfsr_gold.generate(50)  # Need at least 2*degree = 20 bits
    
    print(f"Gold code sequence (50 bits): {gold_sequence}")
    
    reconstructed_poly_gold, reconstructed_L_gold = berlekamp_massey(gold_sequence)
    reconstructed_state_gold = reconstruct_lfsr_state(gold_sequence, reconstructed_poly_gold)
    
    print(f"Reconstructed polynomial: {reconstructed_poly_gold}")
    print(f"Reconstructed state: {reconstructed_state_gold}")
    print(f"Reconstructed degree: {reconstructed_L_gold}")
    
    match_gold, generated_gold = verify_lfsr(gold_sequence, reconstructed_poly_gold, reconstructed_state_gold)
    print(f"Verification: {'✓ PASS' if match_gold else '✗ FAIL'}")
