function goldCodeSequence = generateGoldCodeSequence(simParams)
    % generateGoldCodeSequence Generates a Gold code sequence.
    %
    %   goldCodeSequence = generateGoldCodeSequence(simParams) generates a Gold
    %   code sequence by XORing the outputs of two preferred-pair maximal-length
    %   LFSRs (m-sequences). Gold codes provide a larger family of sequences
    %   with well-controlled correlation properties compared to m-sequences alone,
    %   which is useful in CDMA systems to allow multiple users to share the
    %   same frequency band.
    %
    %   This function is designed to be a component within a larger simulation
    %   framework and expects a 'simParams' struct with the following fields:
    %
    %   simParams.pnPoly1:        Generator polynomial for the first LFSR.
    %   simParams.pnInitial1:     Initial conditions for the first LFSR.
    %   simParams.pnPoly2:        Generator polynomial for the second LFSR.
    %   simParams.pnInitial2:     Initial conditions for the second LFSR.
    %   simParams.bitsPerFrame:   The desired length of the output sequence.
    %
    %   The two generator polynomials must correspond to a "preferred pair" of
    %   m-sequences of the same degree to generate Gold codes with optimal
    %   three-valued correlation.

    %% 1. Create LFSRs for m-sequences
    % Create two comm.PNSequence objects to represent the two LFSRs that will
    % generate the base m-sequences.
    pnGen1 = comm.PNSequence('Polynomial', simParams.pnPoly1, ...
                           'InitialConditions', simParams.pnInitial1, ...
                           'SamplesPerFrame', simParams.bitsPerFrame);

    pnGen2 = comm.PNSequence('Polynomial', simParams.pnPoly2, ...
                           'InitialConditions', simParams.pnInitial2, ...
                           'SamplesPerFrame', simParams.bitsPerFrame);

    %% 2. Generate m-sequences
    % Generate a frame from each PN sequence generator. The output will be of
    % type double.
    mSequence1 = pnGen1();
    mSequence2 = pnGen2();

    %% 3. Generate Gold Code Sequence
    % The Gold code is generated by the bitwise XOR of the two m-sequences.
    % The 'xor' function on double arrays returns a logical array. We cast
    % it back to double to maintain consistency with other parts of the sim.
    goldCodeSequence = double(xor(mSequence1, mSequence2));

end
